# SPDX-License-Identifier: GPL-2.0
GCOV_PROFILE := y

obj-$(CONFIG_CPUQUIET_FRAMEWORK) += cpuquiet.o driver.o sysfs.o cpuquiet_attribute.o governor.o governors/
obj-$(CONFIG_ROCKCHIP_CPUQUIET) += rockchip-cpuquiet.o
